name: call emojistats

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 10 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    call-emojistats:
        uses: IMOitself/emojistats/.github/workflows/start.yml@master
        with:
            username: ${{ github.actor }}
        secrets:
            gh_pat: ${{ secrets.GITHUB_TOKEN }}